# Generated by Django 3.0.3 on 2020-11-13 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(default='no bio...', max_length=300)),
                ('email', models.EmailField(blank=True, max_length=200, null=True, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('image', models.ImageField(default=profiles.models.default_image, upload_to=profiles.models.upload_images_path)),
                ('image2', models.ImageField(default=profiles.models.default_image2, upload_to=profiles.models.upload_images_path2)),
                ('image3', models.ImageField(default=profiles.models.default_image3, upload_to=profiles.models.upload_images_path3)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nationalid', models.CharField(blank=True, max_length=16)),
                ('telephone', models.CharField(max_length=10, null=True, unique=True)),
                ('age', models.CharField(blank=True, max_length=2)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='Your gender', max_length=12)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('friends', models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('YAC', 'TABLE 1'), ('NAC', 'TABLE 2'), ('DEL', 'TABLE 3'), ('KIN', 'TABLE 4'), ('QUE', 'TABLE 5'), ('TAC', 'TABLE 6'), ('MAC', 'TABLE 7'), ('XEL', 'TABLE 8'), ('GIN', 'TABLE 9'), ('WUE', 'TABLE 10'), ('YAK', 'TABLE 11'), ('NOC', 'TABLE 12'), ('DEG', 'TABLE 13'), ('KIT', 'TABLE 14'), ('QUO', 'TABLE 15'), ('GOC', 'TABLE 16'), ('JAC', 'TABLE 17'), ('DAL', 'TABLE 18'), ('KUN', 'TABLE 19'), ('QAE', 'TABLE 20')], max_length=5)),
                ('seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=300)),
                ('video', models.FileField(upload_to='video/%y')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('send', 'send'), ('accepted', 'accepted')], max_length=8)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='profiles.Profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
