# Generated by Django 3.0.3 on 2020-11-13 15:53

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20201113_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=profiles.models.default_image, upload_to=profiles.models.upload_images_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image2',
            field=models.ImageField(default=profiles.models.default_image2, upload_to=profiles.models.upload_images_path2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image3',
            field=models.ImageField(default=profiles.models.default_image3, upload_to=profiles.models.upload_images_path3),
        ),
    ]
