# Generated by Django 3.0.3 on 2020-09-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200924_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nationalid',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='profile',
            name='telephone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
