# Generated by Django 3.0.3 on 2020-09-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200924_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nationalid',
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
