# Generated by Django 3.0.3 on 2020-09-25 12:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0007_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image2',
            field=models.ImageField(default='default.JPG', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image3',
            field=models.ImageField(default='default.JPG', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(default='none', related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
