# Generated by Django 3.0.3 on 2020-09-25 16:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0010_auto_20200925_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nationalid',
            field=models.CharField(default='no Id...', max_length=16),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=models.CharField(default='no Phone...', max_length=10),
        ),
    ]
