# Generated by Django 3.0.3 on 2020-09-30 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_booking_post_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='owner',
            new_name='user',
        ),
    ]
