# Generated by Django 3.0.3 on 2020-10-04 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('-created',)},
        ),
    ]
