# Generated by Django 3.0.3 on 2020-10-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_room_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='table',
        ),
        migrations.AddField(
            model_name='booking',
            name='table',
            field=models.CharField(choices=[('no1', 'NO 1'), ('no2', 'NO 2'), ('no3', 'NO 3'), ('no4', 'NO 4'), ('no5', 'NO 5')], max_length=5, null=True),
        ),
    ]
