# Generated by Django 3.0.3 on 2020-10-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0032_auto_20201009_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.JPG', upload_to='upload_images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image2',
            field=models.ImageField(default='default.JPG', upload_to='upload_images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image3',
            field=models.ImageField(default='default.JPG', upload_to='upload_images/'),
        ),
    ]
