# Generated by Django 3.0.3 on 2020-10-28 07:13

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0034_auto_20201028_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=profiles.models.default_image, upload_to=profiles.models.upload_images_path),
        ),
    ]
