# Generated by Django 3.0.3 on 2020-11-03 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0040_auto_20201103_0801'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
