# Generated by Django 3.0.3 on 2020-11-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0042_profile_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
